name: CI - Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [21]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ matrix.java }}-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties','**/build.gradle*') }}
          restore-keys: |
            gradle-${{ runner.os }}-${{ matrix.java }}-

      - name: Grant execute for gradlew
        run: chmod +x gradlew

      - name: Build jar
        run: ./gradlew bootJar --no-daemon --console=plain -x test

      - name: Run tests
        id: test
        run: |
          set -o pipefail
          ./gradlew test --no-daemon --console=plain | tee gradle-test-output.txt
        continue-on-error: true

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            build/reports/tests
            build/test-results
            gradle-test-output.txt

      - name: Fail workflow if tests failed
        if: steps.test.outcome != 'success'
        run: |
          echo "Tests failed — failing workflow"
          exit 1
