name: CI - Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [21]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: openjdk
          java-version: ${{ matrix.java }}

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ matrix.java }}-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties','**/build.gradle*') }}
          restore-keys: |
            gradle-${{ runner.os }}-${{ matrix.java }}-

      - name: Grant execute for gradlew
        run: chmod +x gradlew

      - name: Build jar
        run: ./gradlew bootJar --no-daemon --console=plain -x test
